version: '2'
services:
  app:
    image: pratikgadoya/golang-errtracker:latest
    restart: always
    volumes:
      - ./:/var/www/html/golang-errtracker
      - gopathvolume:/root/.go
      # - ./postcommand.sh:/usr/local/bin/php-postcommand.sh
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
      - 8888:8888
    # command:
      # - chmod +x postcommand.sh
      # - php-postcommand.sh
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
      - ./golang-errtracker.sql:/docker-entrypoint-initdb.d/golang-errtracker.sql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8085:80
    volumes:
     - /sessions
    environment:
      - "PMA_HOST=database"
      - "PMA_PORT=3306"
      - "MYSQL_ROOT_PASSWORD=secret"
volumes:
  dbdata:
  gopathvolume: